### ISSUE TITLE
Pagination Dots

### ISSUE THREAD

**Issue by charinduedirisuriya** [lehoangnam97/react-native-anchor-carousel#10]
Would be great if this library had a pagination control with dots, or number according to the number of slides available.
 
![GYoJW](https://user-images.githubusercontent.com/33041881/72200500-32b62200-3470-11ea-8fe0-5c861904c8a1.png)

**Comment by pmella16** [comment]
you can use some like this

https://github.com/yasaricli/react-native-dots-pagination

or

https://github.com/pratt3351/react-native-animated-pagination-dot

**Comment by namlehoangdev** [comment]
Great library @pmella16 . @charinduedirisuriya  you can write your own pagination dot too, I wrote it in the new demo https://snack.expo.io/@lehoangnamuit/react-native-anchor-carousel
