### ISSUE TITLE
Need help with current index of carousel

### ISSUE THREAD

**Issue by felixmois** [lehoangnam97/react-native-anchor-carousel#11]
The only thing that I didn’t succeed is to set a variable of my state with the current selected index of the carousel. Can someone help me out with that? It looks like the carousel already know this index because is able to set inactive scale and opacity for the rest of the items. But I need that in my component. Part of my code is:
`export const carouselItems = [
  { text: 'NIR', value: 0 },
  { text: 'Both', value: 2 },
  { text: 'Red', value: 1 }
];

setOptionIndex = index => {
    this.setState({ optionIndex: index });
    this._carousel.scrollToIndex(index);
  };

  _renderItem = ({ item, index }) => {
    const { optionIndex } = this.state;
    return (
      <TouchableOpacity onPress={() => this.setOptionIndex(index)}>
        <Text style={optionIndex === index ? styles.selectedOption : styles.selectedOption}>{item.text}</Text>
      </TouchableOpacity>
    );
  };
<View style={styles.options}>
        <Carousel
          style={styles.carousel}
          data={carouselItems}
          renderItem={this._renderItem}
          containerWidth={sliderWidth}
          itemWidth={100}
          inActiveScale={0.7}
          inActiveOpacity={0.4}
          pagingEnable={true}
          ref={(c) => {
            this._carousel = c;
          }}
          minScrollDistance={30}
          initialIndex={1}
        />
      </View>`

![image](https://user-images.githubusercontent.com/57527104/75445442-10b82680-596e-11ea-9345-3bd006244338.png)
Attached is a small screenshot from my app. I want to know in this screen on what index is the carousel.

**Comment by felixmois** [comment]
I find a solution for my above problem, I post it here maybe someone will need it. The solution was onScrollEnd prop.
`
_onScrollEndHandler = ({ value: currentItemValue }) => {
    this.setState( { currentItemValue })
  };

const options = (
      <View style={styles.options}>
        <Carousel
          style={styles.carousel}
          data={carouselItems}
          renderItem={this._renderItem}
          containerWidth={sliderWidth}
          itemWidth={100}
          inActiveScale={0.7}
          inActiveOpacity={0.4}
          pagingEnable={true}
          ref={(c) => {
            this._carousel = c;
          }}
          minScrollDistance={30}
          initialIndex={1}
          onScrollEnd={(item) => this._onScrollEndHandler(item)}
        />
      </View>`

**Comment by namlehoangdev** [comment]
Thank you !
