### ISSUE TITLE
Calling `getNode()` on the ref of an Animated component is no longer necessary

### ISSUE THREAD

**Issue by tanvoid0** [lehoangnam97/react-native-anchor-carousel#12]
### Using react-native-anchor-carousel gives me the warning below

**FlatList: Calling `getNode()` on the ref of an Animated component is no longer necessary. You can directly use the ref instead. The method will be removed in future release**

**Packages:**
 - react: 16.11.0
 - react-native: 0.62.2
 - react-native-anchor-carousel: 3.1.2

**Smartphone:**
 - Device: Redmi Note 8 Pro
 - OS: Android 10

**Comment by namlehoangdev** [comment]
Thanks for your feedback. I will update soon @tanvoid0

**Comment by namlehoangdev** [comment]
This issue was fixed. Checkout new version 4.0.1. Thank you
