### ISSUE TITLE
Calling `getNode()`

### ISSUE THREAD

**Issue by elouisramsey** [lehoangnam97/react-native-anchor-carousel#19]
I keep getting this error `%s: Calling `getNode()` on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in a future release., FlatList
at node_modules\expo\build\logs\LogSerialization.js:155:14 in _captureConsoleStackTrace
at node_modules\expo\build\logs\LogSerialization.js:41:26 in serializeLogDataAsync` anytime i try to swipe to next carousel

**Comment by namlehoangdev** [comment]
Could you please show me your package.json. I need more information about the version of of react-native and react-native-anchor-carousel

**Comment by elouisramsey** [comment]
` "dependencies": {
    "@react-native-async-storage/async-storage": "~1.15.0",
    "@react-native-community/datetimepicker": "3.5.2",
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/bottom-tabs": "^6.0.4",
    "@react-navigation/native": "^6.0.2",
    "@react-navigation/stack": "^6.0.6",
    "axios": "^0.23.0",
    "expo": "~42.0.1",
    "expo-app-loading": "^1.1.2",
    "expo-status-bar": "~1.0.4",
    "react": "16.13.1",
    "react-datepicker": "^4.2.1",
    "react-dom": "16.13.1",
    "react-hook-form": "^7.15.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-anchor-carousel": "3.1.2",
    "react-native-dotenv": "^3.2.0",
    "react-native-gesture-handler": "~1.10.2",
    "react-native-pager-view": "5.0.12",
    "react-native-reanimated": "~2.2.0",
    "react-native-safe-area-context": "3.2.0",
    "react-native-screens": "~3.4.0",`

using expo

**Comment by namlehoangdev** [comment]
Try version react-native-anchor-carousel version 4.0.1 . It might fix your issue. I created an example here with expo: https://snack.expo.dev/@lehoangnamuit/react-native-anchor-carousel
