### ISSUE TITLE
Supporting RTL?

### ISSUE THREAD

**Issue by creativemind1** [lehoangnam97/react-native-anchor-carousel#4]
Does all images only slides from Left to Right (Arabic Language). I have Arabic Languages images (RTL) which needs swiping from RTL. How can I do that?

**Comment by namlehoangdev** [comment]
Seems you want to change its initial index. You can do that by provide it property **initialIndex** equal to your data length :    initialIndex={data.length}
```
 <Carousel style={styles.carousel}
                      data={data}
                     initialIndex={data.length}
                      renderItem={this.renderItem}
                      itemWidth={200}
                      containerWidth={width - 20} 
                      separatorWidth={20}
                      ref={(c) => {
                          this._carousel = c;
                      }} 
            />
```

**Comment by creativemind1** [comment]
I have like 1000s of item. So setting initialIndex to 1000 is simply crashing off my phone and closing the app

**Comment by namlehoangdev** [comment]
Hi there, I had just updated it to version 2.2.0 which now support Flatlist props. You can use **inverted={true}** for your purpose. For large size data, some props of Flatlist might useful: **removeClippedSubviews, maxToRenderPerBatch, updateCellsBatchingPeriod, initialNumToRender, windowSize**. Take a look at 
[this](https://github.com/filipemerker/flatlist-performance-tips) topic.
