### ISSUE TITLE
How can i render a local image in the uri property ? 

### ISSUE THREAD

**Issue by kasback** [lehoangnam97/react-native-anchor-carousel#8]

**Comment by namlehoangdev** [comment]
Hi @kasback, Is your question about render render local image of React native, seems it's is not relevant to this library. 
But you can use this syntax:

Firtly, import component that you wanna use:
` import {Image} from 'react-native' ;//or import {ImageBackground} from 'react-native';`

to use it 
`<Image source={require('{pathToYourImage}')} />`
for example:
`<Image source={require('./img/check.png')} />`
